name: Sentiment Analysis

on:
  push:
    branches:
      - main

jobs:
  run_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install psycopg2-binary
          pip install pandas
          pip install finvizfinance
          pip install torch
          pip install transformers
          pip install tqdm
          pip install gdown
          pip install jupyter

      - name: Run headlines_extraction notebook
        run: jupyter nbconvert --execute --to notebook --inplace headlines_extraction.ipynb

      - name: Run inference notebook
        run: jupyter nbconvert --execute --to notebook --inplace inference.ipynb
